### ISSUE TITLE
How use with serverless-env-generator

### ISSUE THREAD

**Issue by derevandal** [postlight/serverless-babel-starter#74]
Hi, i'm using [serverless-env-generator](https://www.npmjs.com/package/serverless-env-generator) to protect my env variables with KMS.
But, I can't use with this boilerplate.

.enviroment.yml
```yaml
production:
  INSTAGRAM_MAX_ITEMS: '6'
  YOUTUBE_MAX_ITEMS: '6'
dev:
  INSTAGRAM_MAX_ITEMS: '6'
  YOUTUBE_MAX_ITEMS: '6'
staging:
  INSTAGRAM_MAX_ITEMS: '6'
  YOUTUBE_MAX_ITEMS: '6'
```

serverless.yml
```yaml
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  envFiles:
    - environment.yml
  envEncryptionKeyId: ${env:AWS_KMS_KEYID}

plugins:
  - serverless-env-generator
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
```

webpack.config.js
```js
const nodeExternals = require('webpack-node-externals')
const slsw = require('serverless-webpack')
const Dotenv = require('dotenv-webpack')

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.jsx?$/,
        include: __dirname,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js', '.jsx']
  },
  plugins: [
    new Dotenv()
  ]
}
```
lambda.js
```js
import 'dotenv/config'
import { corsSuccessResponse, corsErrorResponse, runWarm } from '../utils'

const handler = async event => {
/* logic */
}
export default runWarm(handler)
```

Lambda env in console:
![image](https://user-images.githubusercontent.com/1340508/62890574-23dd0f00-bd1a-11e9-9516-69d10ca1d9ab.png)

Could some one help me?

**Comment by WajeehZantout** [comment]
Hey @derevandal, it seems this issue is not related to the starter kit.

After looking into the documentation for [serverless-env-generator](https://github.com/DieProduktMacher/serverless-env-generator#readme), I noticed something missing in your config that might be causing this issue:

```yaml
  envFiles:
    - environment.yml
  envEncryptionKeyId: ${env:AWS_KMS_KEYID} // dev is missing here (https://github.com/DieProduktMacher/serverless-env-generator#3-add-the-plugin-to-your-serverless-configuration-file)
```

And make sure you are creating a KMS key as mentioned in the docs
